name: 🔄 Updater

on:
  schedule:
    - cron: '*/8 * * * 0' # The IP address will update every 30 minutes.
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@master

    - name: Set Environment Variables
      run: |
        echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
        echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
        echo "CLOUDFLARE_LOCATION_NAME=${{ secrets.CLOUDFLARE_LOCATION_NAME }}" >> $GITHUB_ENV
        echo "HOSTNAME=${{ secrets.HOSTNAME }}" >> $GITHUB_ENV
        echo "FAMCF_ACCOUNT_ID=${{ secrets.FAMCF_ACCOUNT_ID }}" >> $GITHUB_ENV
        echo "FAMCF_API_TOKEN=${{ secrets.FAMCF_API_TOKEN }}" >> $GITHUB_ENV
        echo "MLC_ACCOUNT_ID=${{ secrets.MLC_ACCOUNT_ID }}" >> $GITHUB_ENV
        echo "MLC_API_TOKEN=${{ secrets.MLC_API_TOKEN }}" >> $GITHUB_ENV
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
        echo "TELEGRAM_CHAT_ID1=${{ secrets.TELEGRAM_CHAT_ID1 }}" >> $GITHUB_ENV
        echo "TELEGRAM_CHAT_ID2=${{ secrets.TELEGRAM_CHAT_ID2 }}" >> $GITHUB_ENV

    - name: Install Node.js
      uses: actions/setup-node@master
      with:
        node-version: "lts/*"

    - name: Install npm dependencies
      run: npm ci

    - name: Running Gateway Update
      run: node ModemRouterUpdate/startUpdate.js
      continue-on-error: true

    - name: Updating Traffic Values
      run: node ZeroTrustGateway/injectRule.js
      continue-on-error: true

    - name: Updating Parental Control
      run: node ParentalControl/streamCtrl.js
      continue-on-error: true

    - name: Updating Parental Control
      run: node ParentalControl/WiFiOnlyDomains.js
      continue-on-error: true

    - name: Injecting Policy Override
      run: node ZeroTrustGateway/policyOverride.js
      continue-on-error: true
